## Problem Solving and Programing

### Arshad
### Day 18
### Date : 16-MAY-2019

###Day Outcomes
1. 

### Problem 1

#### Problem Statement:
Python Program to read data from a text file

In [14]:
def readFileData(filename):
    f=open(filename,'r')  # First open the file # r stands for only read permissions
    #filedata=f.readline()
    filedata=f.read()
    f.close()           #Close the file finally
    return filedata
    #return filedata2
readFileData('DataFiles/data.txt')

'Data in line 1\nData in line 2\nData in line 3'

In [17]:
def readFileData(filename):
    with open(filename,'r') as f: # with is used to close the file so that we dont need to close it manually

        filedata=f.read()
        return filedata
readFileData('DataFiles/data.txt')

'Data in line 1\nData in line 2\nData in line 3'

In [19]:
def readFileData(filename):
    with open(filename,'r') as f:
        for line in f:                    #To eliminate \n'
            print(line,end = ' ')

        return 
readFileData('DataFiles/data.txt')

Data in line 1
 Data in line 2
 Data in line 3 

In [24]:
def readFileData(filename):
    with open(filename,'r') as f:
        print(f.read())                  #To avoid usage of for loop

    return 
readFileData('DataFiles/data.txt')

Data in line 1
Data in line 2
Data in line 3


In [31]:
def writeIntoFile(filename,data):
    with open(filename,'w') as f: # w is used to write      # 'a' can be used to append to existing data
        f.write(data)
    return
writeIntoFile('DataFiles/fileWrite.txt','First Written Line')

### Appending to the above File

In [36]:
def writeIntoFile(filename,data,mode):
    with open(filename,mode) as f: # w is used to write      # 'a' can be used to append to existing data
        f.write(data)
    return
writeIntoFile('DataFiles/fileWrite.txt','Fourth Appended Line \n','a')

### Problem 2

#### Problem Statement:
Define a function to generate a Marks Data File (txt) for 1300 students such that each mark is entered in a new line.
Marks range from 0 to 100 (inclusive)
Marks are random numbers

In [97]:
import random
def writeMarksIntoFile(filename,n):
    with open(filename,'w') as marksFile:
        for i in range(0,n):
            marks=random.randint(0,100)
            marksFile.write(str(marks)+'\n')
    return
#def printing():
#    for i in range(0,1301):
#        print(random.randrange(0,101))
#        print(end='\n')
writeMarksIntoFile('DataFiles/Marks.txt',1300)

### Problem 3

#### Problem Statement:
Generate a report (txt file) about the marks data above problem,with the following indicators
* Highest Marks:
* Lowest Marks:
* Average Marks:
* No.of students with distinction  (>80) :
* No.of students with First Class  (>60) :
* No.of students with Second Class (>50) : 
* No.of students with Third Class :(>40) :
* No.of Students Failed            (<40) :

In [101]:
import random
def readMarksFromFile(filename):
    marks_li=[]
    with open(filename,'r') as f:
        for x in f:                 #this takes in element instead of index
            marks_li.append(int(x))
    writeMarksIntoFile('DataFiles/reportFile.txt',marks_li)
    
def writeMarksIntoFile(filename,arr):
    dist=0
    first=0
    second=0
    third=0
    fail=0
    with open(filename,'w') as reportFile:
        reportFile.write("Highest is: "+str(max(arr))+'\n')
        reportFile.write("Lowest is: "+str(min(arr))+'\n')
        reportFile.write("Average is: "+str(sum(arr)//len(arr))+'\n')
        for i in range(0,len(arr)):
            if(arr[i]>=80):
                dist=dist+1
            elif(arr[i]>=60 and arr[i]<80):
                first=first+1
            elif(arr[i]>=50 and arr[i]<60):
                second=second+1
            elif(arr[i]>=40 and arr[i]<50):
                third=third+1
            else:
                fail=fail+1      
        reportFile.write("Distinction: "+str(dist)+'\n')
        reportFile.write("First Class: "+str(first)+'\n')
        reportFile.write("Second Class: "+str(second)+'\n')
        reportFile.write("Third Class: "+str(third)+'\n')
        reportFile.write("Failed: "+str(fail)+'\n')
    return
readMarksFromFile('DataFiles/Marks.txt')

## Practicing Map Function

In [106]:

li=[1,2,3,4,5,6]
s=str(li)
s[0]

s=list(map(str,li)) # Map takes 2 parameters
                    # Map takes each element in 'li' and converts them to 'str' format
                    # str denotes that li is converted to string
                    # list denotes that all

s[0]

'1'

In [114]:
li=[1,2,3,4,5,6]
def square(n):
    return n*n
s=list(map(square,li))   # converting element of li into square and make it a list
s

7.490000098187011e-05


[1, 4, 9, 16, 25, 36]

## Timer Example

In [139]:
import timeit
start=timeit.default_timer()
li=[1,2,3,4,5,6]
s=list(map(str,li))
s=[float(i) for i in s]
print(timeit.default_timer()-start)
s

7.569999979750719e-05


[1.0, 2.0, 3.0, 4.0, 5.0, 6.0]

In [152]:
li=[1,2,3,4,5,6,7,8,9,85,86,95,100]
def distinction(mark):
    return mark>=80
dis=sum(map(distinction,li))
dis
dis=sum([2 for i in li if i>80])
dis

8

## External Libraries Practice

In [10]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9,]])

print(a)
type(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray